### ISSUE TITLE
[Bug Report] No apps in the user app list.

### ISSUE THREAD

**Issue by xunil89** [Domi04151309/BatteryTool#1]
I am trying the app on arrow OS android 11 but as per the title in the user app list no app is shown. I have magisk 21.2 and the app has already been allowed to be rooted.

**Comment by Domi04151309** [comment]
Can you please send a screenshot?

**Comment by xunil89** [comment]
![Screenshot_20210109-171250.png](https://user-images.githubusercontent.com/14961235/104102270-f6451e00-529d-11eb-92ca-1894748256b5.png)

**Comment by 4tstar** [comment]
I have the same issue. No apps show in user application.
