### ISSUE TITLE
[Bug Report] root rights not possible

### ISSUE THREAD

**Issue by Jepzelf** [Domi04151309/BatteryTool#10]
**Description**
The app insists on root rights but there is no way to grant them.
The about: box states: no permissions asked.
My device; LG Q7

**Comment by Domi04151309** [comment]
I am not able to reproduce this behavior

**Comment by Jepzelf** [comment]
Perhaps it is an Android issue. Plz see attached screenhot.

On August 7, 2021 7:59:00 AM GMT+02:00, Dominik ***@***.***> wrote:
> I am not able to reproduce this behavior
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Domi04151309/BatteryTool/issues/10#issuecomment-894610344
-- 
Jan Volkers
0611243237

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Jepzelf** [comment]
Does BatteryTool require a rooted phone? If so, plz mention this in Fdroid.

**Comment by Domi04151309** [comment]
Yes it does. Granting superuser permissions is only possible on rooted phones. It's already included in the title.
