### ISSUE TITLE
[Feature Request] Ignore if media is playing

### ISSUE THREAD

**Issue by howyay** [Domi04151309/BatteryTool#13]
**Option to not stop an app if media is playing**

_Add an option switch to the settings page, named "Ignore if media is playing" or similarly, which determines whether the apps added to stop list will be stopped automatically according to other rules (say, automatically stop after screen turns off) when that app is playing media._

<details>
  <summary><b>Additional context</b></summary>

It doesn't seem sensible or desirable that YouTube Music or any other music/podcast apps is stopped  when the screen is off and when the user is listening to it.
</details>

**Comment by howyay** [comment]
Oops, didn't see the merged commit, when can we expect new build to ship to FDroid?

**Comment by Domi04151309** [comment]
A new build will be available in the following week.
