### ISSUE TITLE
Some questions regarding last update

### ISSUE THREAD

**Issue by k2helix** [Domi04151309/BatteryTool#15]
Hello, I've been using this app for months and recently there was an update saying that now there is an option to ignore focused apps. My question is: what does the app understand as focused app?

For example, let's say I'm using F-droid (which I've selected in Battery Tool) and check for updates and, in the meanwhile, I turn off the screen. I understand that if I was in the app before turning the screen off, it will be treated as focused (and hence not killed). But, if I check for updates and then leave the app and turn off the screen, would it still be treated as focused? 
Note that the app is still running and there is a notification that says that it is currently checking for updates.

I've been thinking about this for a long time before this option was released as I'm afraid that if an app is currently being updated from an app store, the store gets killed and thus the app is not updated.

Thank you for creating the app, it is really awesome!

**Comment by Domi04151309** [comment]
For the app, another app is focused if you can see the app on your screen. A running service is not enough for the app to count as focused. In your example, F-Droid would not be focused. 
In case you want to try it out yourself, you can use the Android Debug Bridge to get a list of resumed (focused) apps.
```
adb shell dumpsys activity activities | grep mResumedActivity |  cut -d '{' -f2 | cut -d ' ' -f3 | cut -d '/' -f1
```
The above command returns a list of resumed apps.
For a more technical explanation: The app uses this ADB command to figure out which apps have entered the "resumed" state. When you turn off your display the apps leave the resumed state and enter the stopped state. 
![Lifecycle](https://developer.android.com/guide/components/images/activity_lifecycle.png)
See https://developer.android.com/guide/components/activities/activity-lifecycle#alc (the image is hard to see on dark mode).
Feel free to close this issue if this answered your question.

**Comment by k2helix** [comment]
I see. Definitely you answered my question, thanks!
