### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by StoyanDimitrov** [Domi04151309/BatteryTool#17]
May I suggest to use a translation platform as Weblate to handle the translations? Weblate is open source and as such supports open source projects by allowing them to use the service free of charge. Many great open source projects are already there.

This will greatly improve the experience of translators.

P.S.
It is as easy as `git pull` and `git push` to receive and send translations to Weblate.

**Comment by StoyanDimitrov** [comment]
@Domi04151309, will you merge and release XML translation as pull request if I prepare one? I will be happier to use BatteryTool translated and am fine if you don't want to use translation platform for now but would like to avoid my translation ending up in some forgotten pull request.

**Comment by Domi04151309** [comment]
Feel free to translate the app and create a pull request. I won't implement Weblate for now, because I currently don't have the time (and motivation) to look into it.
