### ISSUE TITLE
[Bug Report] Foreground apps

### ISSUE THREAD

**Issue by Mokura** [Domi04151309/BatteryTool#21]
**Description**
Foreground apps are still being closed - for example, if I open Neo Store, keep it onscreen, and shut off the screen, once I turn the screen back on, Neo Store has been closed.  The focused app option is on, and my close delay set to 0 seconds (closed instantly).  Please let me know if you need me to gather more detailed info.

**Additional information**
 - Device: _Google Pixel 5a/barbet_
 - Android version: _12.1/LineageOS 19.1_
 - Battery Tool version: _1.2.0_
 - Installation source: _F-Droid_

**Comment by Domi04151309** [comment]
As soon as you shut off the screen the app is no longer considered to be in the foreground. This is intentional behavior. See #15 for further details.
