### ISSUE TITLE
[Feature Request] Run as administrator 

### ISSUE THREAD

**Issue by srt54558** [Domi04151309/BatteryTool#23]
Hello, would it be possible to set BattetyTool as an device administrator? In the android 13 notification center it's showing the current running apps in the background. AfWall+ is administrator and can't be stopped, but battery tool can.
![Screenshot_20230507-200110.png](https://user-images.githubusercontent.com/90862487/236694628-a2f3c7d2-ad84-4fbb-8c7f-ea70662173e3.png)

**Comment by Domi04151309** [comment]
This will not be implemented as it is not necessary for the core functionality.
