### ISSUE TITLE
[Bug Report] Screen off due to proximity sensor promts BatteryTool to shut down the apps.

### ISSUE THREAD

**Issue by Rimideem** [Domi04151309/BatteryTool#6]
I have included a calling app (Facebook Messenger) to be managed by BatteryTool. 
When I call, and I place the earpiece on my ear, the proximity sensor turns off the screen. BatteryTool thinks that it has to shut down Messenger because the screen was turned off.

**Comment by Domi04151309** [comment]
That's intended behavior. Do not add calling or messaging apps to the list if you rely on them working after the screen gets turned off.
